sudo: false
language: python
python:
  - "3.7"
  - "3.8"

os: linux

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 freeze

before_script:
  - psql -c 'create database helios;' -U postgres

script: "python3 -Wall manage.py test"

jobs:
  include:
  - dist: xenial
    addons:
      postgresql: "9.5"
  - dist: xenial
    addons:
      postgresql: "9.6"
  - dist: xenial
    addons:
      postgresql: "10"
  - dist: bionic
    addons:
      postgresql: "9.5"
  - dist: bionic
    addons:
      postgresql: "9.6"
  - dist: bionic
    addons:
      postgresql: "10"
  - dist: bionic
    addons:
      postgresql: "11"
